[project]
name = "flashmd"
version = "0.2.9"
requires-python = ">=3.11"

readme = "README.md"
license = {text = "Apache-2.0"}
description = "Accelerated molecular dynamics with large-time-step predictions"
authors = [{name = "flashmd developers"}]

dependencies = [
    "metatrain==2026.2.1",
    "metatomic-ase",
    "vesin>=0.5.4",
    "nvalchemi-toolkit-ops==0.3.0",  # tricks metatomic-ase into avoiding buggy vesin
    "ase",
    "huggingface_hub",
]

keywords = ["machine learning", "molecular modeling", "molecular dynamics"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

# TODO: add project URLs

[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "mypy",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
ignore = ["B018", "B904", "E501"]

[tool.ruff.lint.per-file-ignores]
"**/{tests}/*" = ["D"]

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["flashmd"]

[tool.ruff.format]
docstring-code-format = true

[tool.mypy]
follow_imports = 'skip'
ignore_missing_imports = true
disable_error_code = ["union-attr"]

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore:custom data:UserWarning",
    "ignore:`torch.jit.script` is deprecated:DeprecationWarning",
    "ignore:`torch.jit.load` is deprecated:DeprecationWarning",
    "ignore:`compute_requested_neighbors_from_options` is deprecated and will be removed in a future version:UserWarning",
    "ignore:hf_xet\\.download_files\\(\\) is deprecated:DeprecationWarning",
    "ignore:Due to '_pack_', the 'APICLaunchParamRecord' Structure will use memory layout compatible with MSVC:DeprecationWarning",
    "ignore:`torch.jit.script` is not supported:DeprecationWarning",
    "ignore:`torch.jit.script_method` is not supported:DeprecationWarning",
    "ignore:`torch.jit.script_method` is deprecated:DeprecationWarning",
    "ignore:`torch.jit.load` is not supported:DeprecationWarning",
    "ignore:The 'nvalchemiops.neighborlist' module has been renamed to 'nvalchemiops.neighbors':DeprecationWarning",
    "ignore:From version 0.3.0 onwards, PyTorch is now an optional dependency:DeprecationWarning",
    "ignore:`torch.jit.interface` is deprecated:DeprecationWarning",
    "ignore:`torch.jit.set_fusion_strategy` is deprecated:DeprecationWarning",
    "ignore:the '.*' output name is deprecated:UserWarning",
    "ignore:the '.*' quantity is deprecated:UserWarning",
    "ignore:the '.*' quantity is deprecated:DeprecationWarning",
    "ignore:ModelOutput.quantity is deprecated:DeprecationWarning",
]
